# Generated by Django 4.2 on 2025-08-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_remove_location_from_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='total_seats',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='from_stop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_stop',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination', to='booking.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_source', to='booking.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stop',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
