# Generated by Django 4.2 on 2025-08-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_total_seats_bus_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=5),
        ),
    ]
