# Generated by Django 4.2 on 2025-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_route_stops_bus_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
