# Generated by Django 4.2 on 2025-08-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_route_arrival_time_route_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
