# Generated by Django 4.2 on 2025-08-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_index',
            field=models.PositiveIntegerField(blank=True, help_text='Stop order of destination', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_index',
            field=models.PositiveIntegerField(blank=True, help_text='Stop order of source', null=True),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of the stop along the route (1,2,3...)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='booking.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stop')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
