# Generated by Django 4.2 on 2025-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_pushsubscription_delete_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
