# Generated by Django 4.2 on 2025-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
